### ISSUE TITLE
Wrap Perses AtomMapper into openfe.setup.atommapping

### ISSUE THREAD

**Issue by richardjgowers** [OpenFreeEnergy/openfe#10]
The task of generating a mapping between two ligands is done by an [AtomMapper](https://github.com/OpenFreeEnergy/openfe/blob/main/openfe/setup/ligandatommapper.py#L10) which generates an [AtomMapping](https://github.com/OpenFreeEnergy/openfe/blob/main/openfe/setup/ligandatommapping.py#L13)

There is an abstract base class for defining how an Atom Mapper should function here:

https://github.com/OpenFreeEnergy/openfe/blob/main/openfe/setup/ligandatommapper.py#L10

There is an Atom Mapper in perses here we could assimilate:

https://github.com/choderalab/perses/blob/main/perses/rjmc/atom_mapping.py#L543

**Comment by RiesBen** [comment]
This I think is done :)
