### ISSUE TITLE
Network regression tests in various tests are broken

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe#1033]
Example test where this has now failed: test_minimal_spanning_network_regression

I'm pretty sure this is down to updates upstream with gufe, triaging.

**Comment by IAlibay** [comment]
Ok, I can confirm that `test_minimal_spanning_network_regression` and `test_minimal_redundant_network_edges` from `openfe.tests.setup.test_network_planning` are failing with the latest merge in gufe (https://github.com/OpenFreeEnergy/gufe/pull/408).

It looks like the Lomap mapper's behaviour has changed... which is odd because as far as I'm aware Lomap doesn't have use the hybridization information, nor are we serializing the SMC (I think? might have missed something).

@jthorton do you have any ideas?

**Comment by IAlibay** [comment]
Setting this as "high priority", in the sense that red CI makes it hard for us to merge new PRs or identify deeper issues (which this could also be).

**Comment by IAlibay** [comment]
`test_rbfe_tutorial.py` is also broken for a similar reason I think (i.e. the network changed).

**Comment by jthorton** [comment]
Strange this was not expected, I generated the maximal networks using gufe main and gufe-1.1.0 see the difference [here](https://www.diffchecker.com/OK9Xq569/) the only changes are the stored hybridization values the edges and scores are they same.

**Comment by jthorton** [comment]
Loading these and then creating the minimal spanning tree results in two different graphs for some reason depending if gufe is on main or not, see minimal graphs [here](https://www.diffchecker.com/ijps1ekQ/).

**Comment by IAlibay** [comment]
@jthorton could you post how you created the maximal network? (i.e. what scorer & mapper combo you used).

I'm seeing lots of scores of "1", and I'm wondering if it's just a case that when you have multiple edges with values of 1 you just pick based on a gufe key sort (which will have changed because of the new hybridization info).

**Comment by jthorton** [comment]
I used the same method as the [tests](https://github.com/OpenFreeEnergy/openfe/blob/be3433c031b3c7e5c0444a4ecbbfdc233f82b4de/openfe/tests/setup/test_network_planning.py#L273C1-L286C19) and yes that's what I am narrowing it down to.

**Comment by jthorton** [comment]
Both graphs also have the same total weight of 138 so they seem to be valid minimal-spanning networks, ideally we don't want to have to update this test everytime the gufe key changes do we just want to rewrite it to ensure the total weight of the network is always the same rather than checking for the expected edges?

**Comment by jthorton** [comment]
This [PR](https://github.com/OpenFreeEnergy/openfe/pull/247) introduced edge sorting when creating a graph of a `LigandNetwork` we are probably getting a different sorting now that the gufe key has changed.

**Comment by jameseastwood** [comment]
Sounds like we might need a team-wide discussion about how to solve this. Maybe in a team power hour.

**Comment by mikemhenry** [comment]
I think this is a good plan :+1:

**Comment by atravitz** [comment]
@jthorton can this issue be closed now?
