### ISSUE TITLE
CI doubly installs gufe@main

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe#1035]
a pip install to gufe@main is present in both the environment yaml file and in CI here: https://github.com/OpenFreeEnergy/openfe/blob/main/.github/workflows/ci.yaml#L100

This is redundant / makes debugging compatibility issues with upstream changes difficult.

**Comment by atravitz** [comment]
[this PR](https://github.com/OpenFreeEnergy/openfe/pull/1036) kind of addresses this. It only installs gufe@main once, but it installs it on top of the default environment, which contains the conda-forge released gufe. 

@IAlibay does this seem reasonable to you?

**Comment by IAlibay** [comment]
Yep thanks @atravitz !

On a longer term note - we should have a chat at some point to review whether or not we want to deal with an environment.yaml. Part of the issue is that it's really hard to customize certain things (like pip installs) and installing something on top of an existing environment can be.. painful at times.
