### ISSUE TITLE
Allow ingestion of Perses AtomMappings

### ISSUE THREAD

**Issue by richardjgowers** [OpenFreeEnergy/openfe#11]
Would be nice to be able to ingest an `AtomMapping` object from perses

```python
m = openfe.AtomMapping.from_perses(perses_atommapping)


```

**Comment by IAlibay** [comment]
Unless there's any objections I'll work on this?

I'm already having a deep dive into perses for the hybrid topology stuff, so I might as well carry it on with it?

**Comment by IAlibay** [comment]
Note: potentially blocked by #24 - needs investigation
