### ISSUE TITLE
Proposal/Discussion: Packaging and Versioning of Protocols

### ISSUE THREAD

**Issue by richardjgowers** [OpenFreeEnergy/openfe#149]
SemVer is great and we're going to use it.  Reproducing a Protocol **exactly** requires recreating the Protocol objects (gufe family incl. Transformation, Unit, etc) with the exact version.  This is important as semver would allow a bug fix in the z increment (of a x.y.z version), but a bugfix could (beneficially) alter results quite significantly.  Usually getting the latest version in the same generation of Protocol will be fine though (x in the version above).

Managing multiple versions within a single package is going to be a pain.

So I propose:
- Protocols all are packaged externally to allow their versions to float
- this currently affects the RBFE protocol
- "our" Protocols are dependencies of this package to keep everything "batteries included"
- this repo also serves as the example of what a Protocol would look like

Questions:
- is this sane?
- should this approach also include other things, like Mappers?

**Comment by RiesBen** [comment]
If I understood it correctly then, the openfe repo would then be the toolbox for the protocols repo? And gufe is around and used from both.

Sounds sane to me, if we can clearly separate the the repos. I would rather keep Mappers in the openfe repo and small building blocks for the RBFE pipeline as well, only setting them together should happen then in the new one. Maybe we can also put the usage test jnbs (not developer jnbs) there, so as a User I get one repo with all the useful stuff?

**Comment by richardjgowers** [comment]
this is in progress with FEFlow (and others)
