### ISSUE TITLE
Lomap version issues?

### ISSUE THREAD

**Issue by RiesBen** [OpenFreeEnergy/openfe#156]
@richardjgowers : is it just, me...? I somehow get this error when using the LOMAP Mapper right now! is the 'element_change' param present only in a specific version? 

Error:
![image](https://user-images.githubusercontent.com/12428005/178551972-396aea89-12c1-4cd6-b2e7-4b136071068b.png)

lomap Version:
![image](https://user-images.githubusercontent.com/12428005/178552996-64d446b8-4d9d-4d92-8335-4277d79924f6.png)

Git branch: main or rdfmcs_mapper

**Comment by IAlibay** [comment]
latest version of lomap only now

**Comment by RiesBen** [comment]
ah I see... no conda install then :) 👍 
Awesome that fixed it! merci!

**Comment by IAlibay** [comment]
I can pick up `2.1.0` on conda-forge, that's the one that works here.
