### ISSUE TITLE
Ingest Lomap network file into OpenFE network format

### ISSUE THREAD

**Issue by richardjgowers** [OpenFreeEnergy/openfe#16]
Lomap outputs a file, we should convert from that into a `Network` as best as possible.

**Comment by richardjgowers** [comment]
Won't work, Lomap gives filenames and we want the node IDs to be more than this (at least a SMILES)

**Comment by dwhswenson** [comment]
We can't have a way to load those files into our `Molecule`? (Maybe this isn't for the Lomap recreation milestone, but it isn't clear to me why it's impossible.)

**Comment by IAlibay** [comment]
Possible make it a feature request upstream? It would be a lot easier for lomap to generate the necessary objects and make them available than for us to have to try to process the current output. Plus it makes it a sort of example on how we want things we interact with to work (i.e. essentially "lets not make passing in files something we treat as normal")

**Comment by richardjgowers** [comment]
I thought it'd be nice to have a way to load the legacy files that people might have had, but that won't fly.  Yes we could fix upstream but at this point it's more viable/maintainable to make our new architecture mimic Lomap's functionality rather than fix Lomap's output (and this doesn't also break people's expectation of what OG Lomap creates).
