### ISSUE TITLE
`to_json` calls are broken

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe#167]
All the SmallMoleculeComponent `to_json` serialization tests break - what was the intended behaviour change here?

Btw this needs to be fixed asap.

**Comment by richardjgowers** [comment]
on it

**Comment by richardjgowers** [comment]
Ok I got SMC serialisation working, but `Network.from_graphml()` seems broken and I can't figure it out quickly.  I'll do the fix for molecules so you can proceed and try and get networks working again...

**Comment by IAlibay** [comment]
👍🏽 thanks for working on this!
