### ISSUE TITLE
multiple forcefields support

### ISSUE THREAD

**Issue by insukjoung** [OpenFreeEnergy/openfe#178]
I could not find a way to assign multiple forcefields. A list of forcefields does not seem to be accepted. Is there any suggestion?
```python
topology_settings=TopologySettings(
    forcefield = {
        'protein': [ ff_dir + '/amber/ff14SB.xml',
             ff_dir + '/amber/phosaa14SB.xml' ],
    }
)
```

**Comment by IAlibay** [comment]
Hi @insukjoung, thanks so much for opening this!

The way this works current is this way:

```python
    settings = RelativeLigandTransform.get_default_settings()
    settings.topology_settings.forcefield = {
        'protein': 'amber/ff14SB.xml',
        'solvent': 'amber/tip3p_standard.xml',  # TIP3P and recommended monovalent ion parameters
        'ions': 'amber/tip3p_HFE_multivalent.xml',  # for divalent ions
        'tpo': 'amber/phosaa10.xml',  # HANDLES THE TPO
        'ligand': 'openff-2.0.0.offxml',
    }
```

This is definitely something we need to better document (if this works for you would it be ok if I change the title to make it clear we need to add documentation here?).

I will note that this RBFE protocol is about to change a lot with #142. If you have a potential use case for OpenFE, we'd love to hear your feedback on it. We could possibly add you to the OpenFE slack if you're interested?

**Comment by insukjoung** [comment]
Does this mean that I need to list all the possible phospho-amino-acids like below?
```
'tpo': phosaa10.xml,
'sep': phosaa10.xml,
'ptr': phosaa10.xml,
...
```

Of course, you can edit this issue.
I just started to take a look at this project, but I would be happy to communicate in slack.

**Comment by IAlibay** [comment]
Apologies for never getting back to you on this @insukjoung.

The way in which we deal with FF assignment has now completely changed. Now you just have to provide a list of xmls to `forcefield_settings.forcefields`, you don't need to provide an entry per molecule/residue type.

I'm going to close this issue as completed, but do go ahead and re-open as necessary!
