### ISSUE TITLE
Barebones setup

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe#19]
Please add as desired / tick off as sorted out

We need:

- [x] basic setup.py / setup.cfg / pyproject.toml
- [x] basic directory structure
- [x] license (thanks @richardjgowers !)
- [x] README.md
- [x] environment.yaml?
- [x] dummy workflow in .github folder? (just an action that tests nothing should be fine?)
- [x] pep8speaks?
- [x] coverage / codecov
- [ ] linters?
- [ ] CONTRIBUTING

**Comment by dwhswenson** [comment]
What are we thinking for linters other than pep8speaks? Do we need anything else?

IMO, that's all we need in terms of something directly integrated into GitHub. Personally, I like to use CodeClimate to check complexity/repetition (goes beyond linting!), but I don't think it needs to be a hoop for contributors to jump through. I'll enable it on my fork to keep an eye on potential technical debt. I also like to run `pylint` occasionally, but I don't think we need to enforce style on all the `pylint` warnings.

**Comment by mikemhenry** [comment]
Is there a way to run pep8speaks locally? If we are not using a linter that also takes care of formatting automatically, then it's nice to have something that I can run local before I push.

**Comment by dwhswenson** [comment]
By default I think it's just running [pycodestyle](https://github.com/PyCQA/pycodestyle). pep8speaks has a custom YAML config for pycodestyle; default [here](https://github.com/OrkoHunter/pep8speaks/blob/master/data/default_pep8speaks.yml). You can get similar information from `pylint` or `flake8`.

I use `pylint` locally (when I remember). I think pep8speaks only errors on official errors (codes that start with E).

**Comment by mikemhenry** [comment]
Okay cool, we should probably then include the config that pep8speaks uses so that we get the same errors and warning locally as we do with the bot.

**Comment by mikemhenry** [comment]
We should also add a CONTRIBUTING file, is there something that OMSF is using for this?

**Comment by dwhswenson** [comment]
> Okay cool, we should probably then include the config that pep8speaks uses so that we get the same errors and warning locally as we do with the bot.

Sorry, my writing wasn't clear: pep8speaks has a YAML config for itself; the link was to the default values. pycodestyle uses a [section in `setup.cfg`](https://pycodestyle.pycqa.org/en/latest/intro.html#configuration). But I think the pep8speaks default is basically what you get with no config for pycodestyle. 

> We should also add a CONTRIBUTING file, is there something that OMSF is using for this?

Checked a couple OpenFF repos; didn't see anything. No strong opinions from me on CONTRIBUTING files.

**Comment by IAlibay** [comment]
> We should also add a CONTRIBUTING file, is there something that OMSF is using for this?

I would say maybe we need to kick this up the chain of command? I know Karmen mentioned that they were working on some CLAs for OMSF projects. @richardjgowers would know better here.

**Comment by IAlibay** [comment]
Moving CONTRIBUTING.md to it's own issue - as per slack, close for now.
