### ISSUE TITLE
Implement Scorer Base Implementation

### ISSUE THREAD

**Issue by richardjgowers** [OpenFreeEnergy/openfe#2]
```python

s = Scorer(stuff)

m = Mapper.suggest_mapping(m1, m2)

f : float = s.score(m)
```

**Comment by dwhswenson** [comment]
I can start playing with this one -- for this issue:

1. Do we just need an abstract base class?
2. Do we want to implement a `ScoreCombiner` (or some other name) that takes several `Scorer`s and gives a single output? First version would be sum the scores, but options like max score, geometric mean of scores, etc. would be easy extensions.
3. We had talked about generalizing the idea of `Scorer`s to `Annotator`s. In this case, maybe we return a dict of annotations, with `'score'` being the dict entry used for scores?
4. If we generalize to `Annotator`s, it will be useful for each `Annotator` to have some way of communicating what annotations it provides. This could be with a class attribute (`List[str]`). This attribute could be set by an abstract `Scorer` class, making it transparent to users for that use case, although I'm not entirely sure that I like that idea.

**Comment by richardjgowers** [comment]
1 yes
2 maybe leave that for now
3 I was thinking of tuple of `(score, annotation)` so people can easily discard the annotations (it's a bit more specialised)
4 For now this could just be done with docstrings.  So just stating the resulting network will be annotated in a certain way.
