### ISSUE TITLE
Implement AlchemicalMolecule class

### ISSUE THREAD

**Issue by richardjgowers** [OpenFreeEnergy/openfe#20]
Holds 2x `Molecule` and 1x `AtomMapping`

**Comment by IAlibay** [comment]
I assume here we need it to be both the topology & coordinates?

How about `AlchemicalSystem`? (unless we don't want to have the full system environment here? although long term we will need to support proteins to allow for side chain mutations)

How about:
 - `AtomMapping` -> easily to obtain core, appearing, and disappearing atoms
 - Two interchange objects for each state?
    - Since the API isn't very mature, short term: either two OpenMM `System` objects or two Parmed `Structure` objects? (maybe we should just jump the gun early here and go directly with the interchange API rather than waste time implementing a temporary solution?)

**Comment by dwhswenson** [comment]
What does this add beyond `AtomMapping`, since `AtomMapping` now includes the 2x `Molecule`? Does this still need to be an additional object?

**Comment by richardjgowers** [comment]
I think this isn't required since the Mapping got beefed up a little.  I think `AtomMapping` is enough for edge descriptions.

**Comment by dwhswenson** [comment]
Moving to done as a "not going to do" -- we no longer see this as necessary.
