### ISSUE TITLE
add test invokation from openfecli

### ISSUE THREAD

**Issue by richardjgowers** [OpenFreeEnergy/openfe#214]
Would be nice to have `openfe run_tests` or `openfe validate_install` or something to sanity check an environment.

See:
https://github.com/OpenFreeEnergy/openfe/pull/212#discussion_r1009212330

**Comment by dwhswenson** [comment]
I disagree with running tests from `openfe` CLI.

This makes `pytest` a runtime requirement when installing `openfe`. At that point, there is *already* a command line invocation for the tests: `pytest --pyargs openfe openfecli`. There's no need to pollute the CLI subcommand namespace with that. The only time users will need this is to debug installation, so I think installing an extra tool and having a slightly opaque command is perfectly fine: it's a magic recipe for certain circumstances.

Maybe what you want (and what I think would be useful) is a command that gives installed versions of `openfe` and various key dependencies (e.g., `openff-toolkit`, `openmm`, etc.). Maybe `openfe info` (thinking along the lines of `conda info`).

**Comment by IAlibay** [comment]
One option here is to have a baked in "validation benchmark" which essentially runs a given set of solvation free energies. It wouldn't be a short run, but something that we could technically expect folks to run overnight to check if their build was successful?

**Comment by dwhswenson** [comment]
> One option here is to have a baked in "validation benchmark" which essentially runs a given set of solvation free energies. It wouldn't be a short run, but something that we could technically expect folks to run overnight to check if their build was successful?

Similar to OpenMM's `testInstallation`? I'm in favor of that.

**Comment by richardjgowers** [comment]
this is done via the `openfe test [--long]` command
