### ISSUE TITLE
Move mapper/mapping (LigandAtomMapping and LigandAtomMapper) implementations to gufe?

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe#224]
Recent conversations raised that these implementations may be useful to more than one project.

How best should these classes be shared? Should they be moved to gufe?

**Comment by dwhswenson** [comment]
I started drafting an issue about exactly this yesterday. I'm +1 on this change.

It's probably worth a broader discussion on how existing objects should shift between openfe and gufe (e.g., storage).

**Comment by richardjgowers** [comment]
Slightly disagree, I think gufe is nice as abstract things.  If there's stuff in openfe that is useful to other things I'd rather spin those out (some sort of tools repo for openmm....) and reimport them into openfe.

Ideally version changes in gufe would be rare represent the API changing

**Comment by IAlibay** [comment]
One option here could be to make more or less everything that's not a gufe dependency optional in OpenFE? Then folks could just import relevant re-usable bits from openfe without caring too much about dependency size costs?

**Comment by IAlibay** [comment]
> some sort of tools repo for openmm...

The objects aren't openmm specific right? Could we just create "openfe-tools"? Kinda gets you into namespace packaging though...
