### ISSUE TITLE
Dump system PDB or XML by default

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe#234]
Something I've realise, we don't have a good way to post process coordinates at the moment since we don't have a "topology" equivalent we dump out by default to then pass out to MDA or MDTraj.

**Comment by richardjgowers** [comment]
I'm tempted to say this is just `ChemicalSystem`, but then that doesn't actually necessarily correspond to what was simulated (solvation and/or Protocol having free will).

PDB is awful for this, but also I'm not actually sure if there is a nice Topology format easily read by common tools....

I don't think it would be that hard to write the attributes to json, then have a `moljson_to_mdtraj/analysis/whatever` function.  The subtlety being we're not introducing a format that others are meant to read, but instead an opaque blob from which we offer outward routes.

**Comment by richardjgowers** [comment]
pdbs are created now
