### ISSUE TITLE
atom mapping bonds seem red too often

### ISSUE THREAD

**Issue by richardjgowers** [OpenFreeEnergy/openfe#239]
In the mapping visualisation below, 19:14 is in the mapping, which is marked blue as a transmutation.  The bond is coloured red as not mapped, but arguably should be blue as something which is changing?

![index](https://user-images.githubusercontent.com/9249543/212974973-d1343912-35b2-4fd8-9521-c82a33f765fe.png)

**Comment by RiesBen** [comment]
Just double checking my intuition:
BLUE: bond type changing - (MolA 20-> 21 | MolB 21->20)
RED: bond deletion - (MolA 19->nothing | MolB 14->27)
(NOColor/Yellow): nothing changes on the bond (on graph level - ff will modify params like bond length etc.) ? (MolA 19->20 | MolB 14-> 21)
