### ISSUE TITLE
Serialization of get_results is causing quickrun to fail when applying it to the OpenMMRBFE protocol

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe#240]
As reported by David Huggins:

`openfe quickrun -o output/solvent_results.json -d trajectories solvent_trans.json`
leads to:
`TypeError: Object of type Quantity is not JSON serializable`

This appears to be due to `get_estimate` returning Quantities.

**Comment by dwhswenson** [comment]
This will be resolved by openfreeenergy/gufe#110 (specifically, the stuff that had previously been openfreeenergy/gufe#105).

**Comment by richardjgowers** [comment]
fixed by 0b09743 it was actually because the method was returning openmm Quantities not openff Quantities
