### ISSUE TITLE
ValueError: mapping .... deviates by more than 0.5

### ISSUE THREAD

**Issue by djhuggins** [OpenFreeEnergy/openfe#242]
When testing the software, some calculations fail reporting "ValueError: mapping .... deviates by more than 0.5" In the cases I am looking at, this seems to be caused by hydrogen atoms on a methyl that are greater than 0.5 A away due to a simple torsion rotation. I confirmed that this is fixed by setting atom_overlap_tolerance to 1.0. I guess it would also be fixed by overlaying the ligands in a way to overlap the hydrogen atoms.

However, you could consider increasing the default tolerance to 1.0 A unless this impacts performance. 

In any event, I suggest reporting the atom names/numbers that cause the error so that the user knows what to try and fix.

**Comment by IAlibay** [comment]
@djhuggins - apologies about the delay here, we've changed this now to warn but not fail. We've decided that the responsibility on getting mappings right is down to the mapper, not the protocol.
