### ISSUE TITLE
Minor API breaks to make

### ISSUE THREAD

**Issue by dwhswenson** [OpenFreeEnergy/openfe#251]
As we push toward a stable 1.0 release, there are a number of minor changes I'd like to make before we lock the API. This issue is to cover minor changes like renaming and restructuring. These require essentially no code, but will make a difference for user experience. The goal here is to ensure consistency in the API.

The plan is to update the list here as we think of more, to keep this as one issue set to this milestone.

- [x] Network planner naming
- [x] Flatten `setup`?
- [x] `network.py` => `ligandnetwork.py`; `Network` => `LigandNetwork`
- [x] Rename protocol as a `Protocol`
- [ ] Rename `quickrun`
- [x] Remove `utils.errors`
- [x] Remove `utils.molhashing`

### Network planner renaming

We're very inconsistent in our naming of network planners. We have:

* `generate_radial_network`
* `minimal_spanning_graph`
* (in PR #245): `maximal_network`

Decisions:
* `generate_` or just use the name of the network type?
* `network` or `graph`? (I prefer `network`, since that's our object name, too)
* keep `radial` or switch to more widely-used `star_map`?

### Flatten `setup`?

We have a separate `setup` subpackage from the days we were planning to be a namespace package. For typical use, a lot of what users need is in `setup`. Is it worth flattening the namespace? That is, instead of `openfe.setup.LomapAtomMapper` it would just be `openfe.LomapAtomMapper`.

### `network.py` => `ligandnetwork.py`; `Network` => `LigandNetwork`

These names date back to when we were just working on ligand network generation, and are too generic.

### Rename protocol as `Protocol`

Our protocol is called `RelativeLigandTransform` This should be `RelativeLigandTransformProtocol`. There has been user confusion when someone confused this class with a `Transformation`.

### Rename `quickrun`

It's a terrible name. Keep in mind that the output format for a long term solution like this will not be what we have now, but that @richardjgowers wants to keep this output format around mainly for its debug usefulness.

### Remove `utils.errors`

This is hardly used, and can be replaced with `abc` decorators.

### Remove `utils.molhashing`

This is no longer used.

**Comment by IAlibay** [comment]
From today's meeting:
- RelativeLigandTransformProtocol -> RelativeLigandProtocol
- Otherwise lgtm from @richardjgowers and @IAlibay

**Comment by richardjgowers** [comment]
still need to rename quickrun

**Comment by richardjgowers** [comment]
quickrun is staying!
