### ISSUE TITLE
Add option to dump system to xml

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe#260]
Based on call with Joe Bluck.

**Comment by richardjgowers** [comment]
probably TOML not YAML, but yes

https://ruudvanasseldonk.com/2023/01/11/the-yaml-document-from-hell

**Comment by IAlibay** [comment]
Actually I was being distracted here, I meant XML 😅

**Comment by richardjgowers** [comment]
duplicate of #234
