### ISSUE TITLE
Using GAFF forcefield for ligands

### ISSUE THREAD

**Issue by Rmadeye** [OpenFreeEnergy/openfe#277]
Hello,
How to properly use (or is it possible at all) to use GAFF forcefield for the system generation? I tried (in many ways) combinations like:
```
topology_settings=TopologySettings(
        forcefield = {'protein': 'ff14SB.xml',
                      'ligand': 'amber/gaff-2.11.xml',
                      'solvent': 'amber/tip3p_standard.xml',
                      'ions': 'amber/tip3p_HFE_multivalent.xml'},
    )
```
However it always fails due to ` Can't find specified SMIRNOFF force field` or something similar.
Regards,
Rafal

**Comment by IAlibay** [comment]
Hi @Rmadeye!

Unfortunately the current RBFE protocol only support openff smirnoff forcefields for small molecules. We are currently in the process of changing our setting system (https://github.com/OpenFreeEnergy/openfe/pull/267), once this is done, we should be in a place to enable the gaff versions supported by openmmforcefields.

I'll keep this issue open and update you as soon as possible.

**Comment by Rmadeye** [comment]
Thank you!

**Comment by IAlibay** [comment]
A year late on updating things here apologies. This was addressed at some point ~ middle of last  year, it should be possible to pass an openmmforcefields gaff version in the force field settings.
