### ISSUE TITLE
[docs] Settings docs

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe#297]
- [ ] Make pydantic autodocs work & settings exposed (requires #267)
- [ ] Have user docs on settings

**Comment by richardjgowers** [comment]
This sounds like it's detailing the RHTP settings right?  The settings system in general will be covered in #302 right?

**Comment by richardjgowers** [comment]
So is maybe a duplicate of #296 ?

**Comment by IAlibay** [comment]
So ideally settings are linked to but not directly in the docstring for RHTP?

**Comment by richardjgowers** [comment]
this PR seems to have hit this: https://github.com/OpenFreeEnergy/openfe/pull/766

This page and similar seem to be doing the job https://docs.openfree.energy/en/latest/reference/api/openmm_rfe.html
