### ISSUE TITLE
[docs] How do I produce an atom mapping

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe#300]
- [ ] Add userguide docs on "how do I create an atom mapping"

**Comment by dwhswenson** [comment]
Documented under "Creating a network completely from scratch" in here: https://github.com/OpenFreeEnergy/ExampleNotebooks/blob/0b5aafe9104ae6faef80093846cc8007c20eb260/networks/ligand_networks_for_developers.ipynb

**Comment by richardjgowers** [comment]
done here: https://docs.openfree.energy/en/stable/cookbook/creating_atom_mappings.html
