### ISSUE TITLE
[docs] Dealing with Protocols docs

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe#302]
- [ ] Add a broad "how do I deal with protocols, run units, and access results" set of userguid docs.

**Comment by richardjgowers** [comment]
@IAlibay this sounds like it's in a chain of "getting started docs"

1. how do I load my stuff? (goes up to ChemicalSystems) #299 
2. how do I map my stuff? (goes up to Mappings) #300 
3. how do I now put these into a Protocol? (this issue)
4. then the next step would be networks etc, but we've not yet got

**Comment by IAlibay** [comment]
So here my view is that we need to tell folks the broad idea of a protocol - i.e. Protocol makes dags, dags have units, etc...
