### ISSUE TITLE
[docs] explain existence of gufe package for developer minded people 

### ISSUE THREAD

**Issue by mikemhenry** [OpenFreeEnergy/openfe#306]

**Comment by richardjgowers** [comment]
we currently are faking/spoofing various objects to make them look like they're native to openfe package, e.g. https://docs.openfree.energy/en/latest/reference/api/generated/openfe.SmallMoleculeComponent.html

this issue probably boils down to somewhere we should have some text explaining that gufe exists and if you're looking to hack directly on these objects you probably ought to look at the gufe package.

**Comment by mikemhenry** [comment]
Okay so it sounds like we just want to inject a note for everything that we pull from the gufe api docs saying something like "api doc reproduced here for convince, see `gufe` for more details
