### ISSUE TITLE
[docs] troubleshooting your installation 

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe#313]
Things like:
- checking PYTHONPATH issues
- checking version problems
- are you running the latest versions of openfe/gufe?

**Comment by mikemhenry** [comment]
I will have a debugging script that a user can run as well, I was thinking it would be good to incorporate a few of these steps/questions in a bug report template as well

**Comment by mikemhenry** [comment]
#733 is where I will work on this one

**Comment by mikemhenry** [comment]
I think for now I want this to be mostly info to send to us, but later we can make the script actually suggest something like "A newer version of GUFE is available"
