### ISSUE TITLE
use FloatQuantity from openff models

### ISSUE THREAD

**Issue by richardjgowers** [OpenFreeEnergy/openfe#335]
there's a nasty hash bug where ints and floats are giving different strings, e.g. here: https://github.com/OpenFreeEnergy/openfe/blob/main/openfe/protocols/openmm_rfe/equil_rfe_settings.py#L268 starts as 1(int)/picosecond, then becomes 1.0/picosecond on to_dict/from_dict cycle.

**Comment by richardjgowers** [comment]
note we might have to drop `from __future__ import annotations` to get this to work see: https://github.com/pydantic/pydantic/issues/2411

**Comment by mikemhenry** [comment]
I think we need to keep that if we support < python 3.10? I would also be fine only supporting python 3.10+
