### ISSUE TITLE
mapping option in Lomap

### ISSUE THREAD

**Issue by xy127** [OpenFreeEnergy/openfe#348]
Hello,

How to properly select mapping option of LOMAP when doing FEP for following molecules sets from left to right.  I used the same setup in the tutorial,  but got incorrect results.  Too many atoms are to be pertubated. I expected only the atoms marked in yellow to be pertubated
![mapping](https://user-images.githubusercontent.com/68721729/232323030-ad6278ea-943c-467a-97c4-291c5dbd3622.png)
![image](https://user-images.githubusercontent.com/68721729/232323684-3d7b80d8-c3e9-45f4-b43d-4c713648d2fb.png)

command used:
`
network = generate_radial_network(ligands=ligand_mols[1:],
                                  central_ligand=ligand_mols[0],
                                  mappers=[LomapAtomMapper(threed=True, element_change=False),])
`

**Comment by IAlibay** [comment]
@xy127 do you get the right behaviour of you set `element_change` to True?

**Comment by xy127** [comment]
> @xy127 do you get the right behaviour if you set `element_change` to True?

No, it got worse. More atoms get pertubated.

**Comment by richardjgowers** [comment]
@xy127 Lomap won't like mapping the secondary amine group as it involves a ring breakage.  I think if you set `element_change=True` you should get all heavy atoms from the two fused rings though (assuming they have good 3d overlap)
