### ISSUE TITLE
Capitalize all instances of `protocol`?

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe#350]
There's a bit of inconsistency on whether or not we capitalize Protocol. Should we? If so, let's make sure we're consistent in the docs!

**Comment by richardjgowers** [comment]
Probably yes as a rule, if we're referring to an instance of a (sub)class.

**Comment by dwhswenson** [comment]
I think there are cases where I'm referring to the concept of a protocol, distinct from a `Protocol` (which should also be at least in monospace, and ideally linked to the docs)
