### ISSUE TITLE
Add CLI skeleton

### ISSUE THREAD

**Issue by dwhswenson** [OpenFreeEnergy/openfe#36]
Create a basic CLI framework that can be used with subcommands.

**Comment by IAlibay** [comment]
Should this be a separate package that sits on top of the `openfe` one?

Like something a bit like what some folks are doing here? https://github.com/MDAnalysis/mdacli

(I've not been keeping on top of the mdacli project so I don't vouch for the approch, more the idea of having a separate package for it).

**Comment by IAlibay** [comment]
I doubt it'd be that heavy, I guess it's all down to how you organise it.

**Comment by dwhswenson** [comment]
OPS also has a separate CLI: http://github.com/openpathsampling/openpathsampling-cli. That was partly done to separate requirements, but mainly because most of the early work on it was just me goofing around in private, without expectation that it would actually become "a thing."

Click only requires anything if you're on Windows or Python < 3.8: https://github.com/pallets/click/blob/49164faca678dd476f1b11a2584fd0e1c6be70b2/setup.py#L5-L8

**Comment by dwhswenson** [comment]
CLI would be like OPS CLI -- thin wrappers around functionality in the library.

**Comment by dwhswenson** [comment]
I think I might make this a separate package within the repo (and distributed together), as opposed to a subpackage of openfe. That is, the import would be `openfecli` or maybe `openfe_cli`, not `openfe.cli`. It would still be included in `pip install openfe`.

The reason is that otherwise the whole package would be imported every time anything is done with the CLI, including running `--help` or finding tab completions. If our library imports get even slightly heavy, then we'll want to delay the imports in the CLI. (OPS inherits a slow import from netcdf4; requires delayed imports when writing the CLI to keep it responsive.)

**Comment by richardjgowers** [comment]
@dwhswenson sounds good, feel free to go ahead with this.

**Comment by mikemhenry** [comment]
@dwhswenson I was convinced that I wanted the package to not be separate but you changed my mind, making the cli tab complete and `--help` be fast is really important for a good user experience. Then we can also handle any lazy loading optimization we want to do in the CLI package.

**Comment by dwhswenson** [comment]
@mikemhenry : To be clear, there are two separate questions here -- package import and repo structure. I think the decision here is single repo, two packages. So repo structure is something like:

```
openfe/
   openfe/     # library
   openfecli/  # command line
   setup.py    # setup stuff used for both: single project (install both at once); different import
   setup.cfg
```

This also ties versioning together, so the version numbers are always identical.

**Comment by dwhswenson** [comment]
My general approach here is going to be to copy as much as is reasonable from both code and ideas from the OPS CLI, because (1) I'm pretty happy with how that turned out; (2) code is MIT.

Is there any opposition to this? I was thinking I'd do a quick refactor on OPS CLI so that the infrastructure is completely independent (it is already mostly independent). Then I could copy the code in here. I could instead make an upstream dependency, but I think I'd rather just vendor a couple files. We could update by diff/patch when needed (which I don't think will be often.)

Here are the files I would add. The functionality is more than we need now, but reusing existing files is faster than writing something custom and less functional.

* [**`plugin_management.py`**](https://github.com/openpathsampling/openpathsampling-cli/blob/main/paths_cli/plugin_management.py): Generic plugin management system. This makes it easy for users to create many different kinds of plugins. At first, we would use it internally to register new subcommands. In the (distant) future, we could have non-command types of plugins (custom `AtomMapper`s, `NetworkPlanner`s, etc. provided by outside packages and available within the CLI). It also provides the ability (again, distant future) for users to install these plugins either in a specialized directory (like `~/.openfe/plugins` for quick home-brewed stuff) or via namespace packages in a predefined namespace (`openfe_plugins`?) for things distributed via PyPI/conda and more properly maintained.

    This is definitely more functionality than we need now, but it's easier to copy the whole of the functionality than it is to sort out what methods are and aren't needed.

* [**`cli.py`**](https://github.com/openpathsampling/openpathsampling-cli/blob/main/paths_cli/cli.py): Core CLI setup. Allows different subcommands to be in different "sections" when shown in help. Registers subcommands from plugins. Allows a `--log` parameter to be passed to `openfe` to set logging configuration from a `logging.conf` file.

**Comment by mikemhenry** [comment]
Got it, thanks for explaining. I think vendoring/modifying those should be fine and save time.
