### ISSUE TITLE
`UnboundLocalError: "local variable 'ana' referenced before assignment"` in `RelativeHybridTopologyProtocol`

### ISSUE THREAD

**Issue by dotsdl** [OpenFreeEnergy/openfe#360]
When the `RelativeHybridTopologyProtocol` fails, it appears that it isn't always getting to the point [where the `MultiStateSamplerAnalyzer` is defined](https://github.com/OpenFreeEnergy/openfe/blob/793b8173060c4515139288454de94eefd318db7a/openfe/protocols/openmm_rfe/equil_rfe_methods.py#L667), so when the exception is raised and it tries to `ana.clear`, another exception is raised: `UnboundLocalError: "local variable 'ana' referenced before assignment"`

This can be fixed by moving the `MultiStateSamplerAnalyzer` definition before the `try` that it's currently inside of.

**Comment by IAlibay** [comment]
I think eventually I want to just move all of that to a separate method that cleans up after itself, for now let's just move that bit of the code straight after the analyzer is created & used.
