### ISSUE TITLE
image building is failing

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe#362]
see: https://github.com/OpenFreeEnergy/openfe/actions/runs/4771819978/jobs/8490330342

Something is up with the tests, did we somehow correct but break (at least a standard pytest --pyargs call seems to work in #320)? pinging @mikemhenry and @dwhswenson

**Comment by dwhswenson** [comment]
Looks like a bad gufe key in the protocol: affecting both the hard-coded stable key, and the hard-coded repr value.

Not sure what the difference is; this is as far as I'm getting at 10pm on Saturday night.

**Comment by dwhswenson** [comment]
It looks like this was already fixed? @IAlibay, did you fix this in https://github.com/OpenFreeEnergy/openfe/commit/8b2a6add2f0e7837e0922530c3852bb387a980e3?

**Comment by mikemhenry** [comment]
Must have? Or someone did, docker builds are working fine on `main`

**Comment by IAlibay** [comment]
Let's assume it's fine and call it a day?
