### ISSUE TITLE
Add method to visualise an atom mapping

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe#37]
Essentially we'd want our own version of what perses does here: https://github.com/choderalab/perses/blob/a8b490af0e4682082dfa442717ef45c1bd61f538/perses/rjmc/atom_mapping.py#L183-L310

See here for perses notebook: https://github.com/choderalab/perses/blob/master/examples/atom-mapping/Atom-mapping.ipynb

Use case: "I'm sitting in a notebook and I want to cycle through my atom map and see what's going on in each edge".

**Comment by richardjgowers** [comment]
And also

https://github.com/OpenFreeEnergy/Lomap/blob/main/lomap/graphgen.py#L807

**Comment by richardjgowers** [comment]
@mikemhenry this might be a fairly well defined issue, and there's plenty of examples of how to do this for rdkit molecules in the lomap repo (or elsewhere)

**Comment by mikemhenry** [comment]
Sounds good! I will take this on.
