### ISSUE TITLE
Automate Release Version Bumping in Docs

### ISSUE THREAD

**Issue by mikemhenry** [OpenFreeEnergy/openfe#375]
RE: https://github.com/OpenFreeEnergy/openfe/pull/371#issuecomment-1526136247

I am thinking it would be nice if we had an action that would generate the release notes/github release + update the package versions. This could be triggered when a tag is pushed that matches `v*`. The one issue is that it might mess up read the docs where "stable" would point to a version of the docs without the version updates, but maybe the automation could re-tag that commit (in a way that doesn't trigger a big loop). The other idea is to get the version dynamically.

**Comment by dwhswenson** [comment]
This should work to have Sphinx show the installed version (assuming RTD sees the correct version). With a little work from `packaging` to round it down so it is always the most recent release, whether `stable` or `latest` -- isn't that what we need to automate it? It just means replacing part of your URL with the `|version|`.

```diff
--- a/docs/conf.py
+++ b/docs/conf.py
@@ -14,6 +14,8 @@ import os
 import sys
 sys.path.insert(0, os.path.abspath('../'))

+import openfe
+version = openfe.__version__

 # -- Project information -----------------------------------------------------

diff --git a/docs/index.rst b/docs/index.rst
index adb7606..658755f 100644
--- a/docs/index.rst
+++ b/docs/index.rst
@@ -6,6 +6,8 @@
 Welcome to OpenFE's documentation!
 ==================================

+OpenFE |version|
+
 .. toctree::
    :maxdepth: 2
    :caption: Contents:
```
