### ISSUE TITLE
Migrate scoring functions from Lomap

### ISSUE THREAD

**Issue by richardjgowers** [OpenFreeEnergy/openfe#4]
Scorers from `lomap.mcs.MCS` to port:

- [ ] `mcsr`
- [ ] `mncar`
- [ ] `tmcsr`
- [ ] `atomic_number_rule`
- [ ] `hybridization_rule`
- [ ] `sulfonamides_rule`
- [ ] `heterocycles_rule`
- [ ] `transmuting_methyl_into_ring_rule`
- [ ] `transmuting_ring_sizes_rule`
- [ ] the matrix score, which is a product of all(?) of the above

Note, Lomap uses a score where 1.0 is "good"/viable and 0.0 is bad.  We use weights where 0.0 is good and larger scores are less good.  Can use `1 - lomap` to get same effect?

**Comment by dwhswenson** [comment]
Based on discussion in #6, this should be done after #9. Moving this out of Available.
