### ISSUE TITLE
Add contributing and code of conduct information

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe#42]
Follow-up from #19 

This will need working upstream with the OMSF folks, we'll probably need to consider things like CLA and maybe an OMSF-wide CoC policy?

**Comment by IAlibay** [comment]
Tagging in @karmencj - TLDR of discussions is that this is currently being worked on within OMSF.

**Comment by karmencj** [comment]
@IAlibay, CoC is on the agenda for the next OMSF BoD meeting and the CLAs are in preparation, we should have it any day now. We can then create a more specific contribution guidelines.
