### ISSUE TITLE
Question: OPENFE

### ISSUE THREAD

**Issue by satvikkg** [OpenFreeEnergy/openfe#422]
Is there a way to calculate the absolute binding free energies ?

**Comment by IAlibay** [comment]
Hi @satvikkg - thanks so much for your interest, we're currently working on it (see PR #237 for our start towards it). We'll update as soon as we have something working.

**Comment by wenchangzhou-qtx** [comment]
Hey @IAlibay just to follow up on this topic, is there anything for us to try ABFE now?
