### ISSUE TITLE
Old installation docs need updating

### ISSUE THREAD

**Issue by xyzmjf** [OpenFreeEnergy/openfe#432]
NB - Installation instructions here are out of date. 
https://github.com/OpenFreeEnergy/openfe
The latest install docs are actually here
https://docs.openfree.energy/en/stable/installation.html

**Comment by xyzmjf** [comment]
Having old installation docs laying around is very problematic if they are found by new users. I am sure the developers which version of these is the latest and greatest but poor old Joe Public does not. It means they end up up with an old or incorrect install and even if they do find the new docs, they have to work out how to clean up the old one first. Trust me it is a major headache and the surest way to lose potential new users.

**Comment by IAlibay** [comment]
@xyzmjf forgive my likely sillyness here, but the readme instructions point to the actual docs you link to? The only difference is that the readme also include developer instructions?

**Comment by IAlibay** [comment]
Closing as I believe I already addressed this a few weeks back (see slack).
