### ISSUE TITLE
Documentation setup

### ISSUE THREAD

**Issue by dwhswenson** [OpenFreeEnergy/openfe#47]
In discussions, we've agreed that we want a documentation setup that is mostly based on Jupyter notebooks, with some room for additional RST files and the ability to get good autodoc API generation. A lot of this can be seen in the [documentation for Contact Map Explorer](https://contact-map.readthedocs.io/en/latest/), source [here](https://github.com/dwhswenson/contact_map/tree/master/docs). Most of the hard work is done by `nbsphinx`.

### The tricky part: notebooks need to be in the sphinx docs/ directory

We need to get the notebooks into the right place in the docs tree, so that `nbsphinx` can find them. In `contact_map`, the notebooks are in the repository, and this is done by [copying with `shutil` in the `conf.py`](https://github.com/dwhswenson/contact_map/blob/b6d2461fa9125c6694d4e72a2f00582d5ab27260/docs/conf.py#L30-L34). However, we don't want to include the notebook repo with the main code.

In OpenPathSampling, I wrote a [script to copy files into the sphinx docs directory from any of local file, GitHub repos, or GitLab repos](https://github.com/openpathsampling/openpathsampling/tree/master/docs/copyfiles). It is based on a YAML input file, and so requires pyyaml to be installed in the doc building environment. It also must be run as a script before building the docs.

Neither of these are perfect for us, but I think that together they can be pieced into a good solution. Ideally, our solution would:

1. Copy the files over from another GitHub repo.
2. Run when `conf.py` is run, instead of in a separate script.

### Other things that might be useful

* [Autogenerate binder links.](https://github.com/dwhswenson/contact_map/blob/b6d2461fa9125c6694d4e72a2f00582d5ab27260/docs/conf.py#L408-L431) Credit to my co-dev on `contact_map` for this work.
* [Getting version from installed code.](https://github.com/dwhswenson/contact_map/blob/b6d2461fa9125c6694d4e72a2f00582d5ab27260/docs/conf.py#L44-L45) I don't think this is default Sphinx, but since I usually need the code I'm documenting installed (for autodoc), I figure you might as well get the version from the installation.

**Comment by IAlibay** [comment]
A thought before I forget - since we're likely going to use the https://openfree.energy/ domain here, are we interested in using subdomains for the api and userguide (something like docs.openfree.energy and userguide.openfree.energy)?

Just thinking - assuming all notebooks are userguide related, we probably wouldn't need to try to move things between repos on CI or release right? We can just keep a repository_dispatch to trigger both release workflows at the same time.
