### ISSUE TITLE
NES and FEP+ network ingestion

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe#506]
We need light wrappers to take in serialized NES and FEP+ networks and spit out LigandNetworks

**Comment by dwhswenson** [comment]
I've shifted against putting a CLI wrapper around this in 0.12. This is "yet another network generator", and I think we need an deeper internal conversation on how those will be supported in the CLI.

So I'm 100% for including this at the Python layer in 0.12 if it can be done, but I'd prefer that we decide on how to put this (and radial networks/star maps, and future stuff) into the CLI after the whole team has had a chance to create a well-considered long-term strategy. If that's enough to delay this from 0.12 at the Python layer, I'm fine with that, too.
