### ISSUE TITLE
Add duecredit support

### ISSUE THREAD

**Issue by mikemhenry** [OpenFreeEnergy/openfe#528]
https://github.com/duecredit/duecredit

**Comment by richardjgowers** [comment]
@mikemhenry I'm a fan of duecredit.  As well as tagging functions, I think we'll want to figure out how to propagate this through to results output dict so that it is always included in the output.

**Comment by mikemhenry** [comment]
Oh I like that even better! I was thinking that with the plug and play nature, we can annotate parts of our code base and then for the protocol author's guide we can include it as well. Eventually, when we build "The Free Market" where people can see all the different protocols out there, we could either require it, or write the injections for things listed.
