### ISSUE TITLE
ci: test_dry_run_user_charges is flakey

### ISSUE THREAD

**Issue by richardjgowers** [OpenFreeEnergy/openfe#532]
see: https://github.com/OpenFreeEnergy/openfe/actions/runs/5961342953/job/16170361902?pr=521

**Comment by mikemhenry** [comment]
~This is a test I really wouldn't expect to be flaky.~

Should we make the dry run dryer and skip minimization?

**Comment by IAlibay** [comment]
> ~This is a test I really wouldn't expect to be flaky.~
> 
> Should we make the dry run dryer and skip minimization?  

it's a bit of a complex pre minimisation step, I'd probably ask that we don't mess with that if we can avoid it atm.

Flakeness might just be due to the harshness of the partial charges - just divide by a larger number and see what happens

**Comment by IAlibay** [comment]
@richardjgowers unfortunately I think the entire macos set of tests is flaky, see #509.

**Comment by dwhswenson** [comment]
> unfortunately I think the entire macos set of tests is flaky,

To clarify, we've seen that macOS on GitHub actions is flaky. This may be a consequence of how GitHub sets up its macOS runners. As far as I have seen, the issues in #509 don't occur when running on macOS in the real world.

But this gets back to my original question: Is this likely to be a macOS-specific thing, or is this genuine flakiness?

**Comment by IAlibay** [comment]
How much trouble would it be for someone to run CI in a loop a dozen times and see what actually fails?

**Comment by dwhswenson** [comment]
> How much trouble would it be for someone to run CI in a loop a dozen times and see what actually fails? (locally that is)

Not much trouble; may not be informative. That catches ~1/12 flakiness, which this issue almost certainly isn't. But ``for ii in `seq 12`; do pytest -v; done`` isn't particularly difficult to type... running now.

**Comment by IAlibay** [comment]
> Not much trouble; may not be informative. That catches ~1/12 flakiness

I mean choose the egg pack size you want to test, I'll also favor base 20 increments like a good French citizen.

**Comment by richardjgowers** [comment]
here's it being flakey on ubuntu: https://github.com/OpenFreeEnergy/openfe/actions/runs/6001278107/job/16275099362?pr=536#step:8:1320
