### ISSUE TITLE
`generate_radial_network` does not check if `central_ligand` is in `ligands`

### ISSUE THREAD

**Issue by Yoshanuikabundi** [OpenFreeEnergy/openfe#544]
There is no check in `generate_radial_network` that the `central_ligand` is not present in `ligands`. Instead, if `ligands` includes `central_ligand`, an edge is created from `central_ligand` to `central_ligand`. This causes the resulting network to include a transformation from the central ligand to itself. This does not appear in the current visualization method `plot_atommapping_network` but could cause spurious calculations to run, I'm not sure. The edge is certainly included in `LigandNetwork.edges` and `LigandNetwork.graph.edges`.

I think this should either raise an exception or silently delete the useless edge, possibly with an optional argument to allow it, and the behavior should be clearly documented in the docstring.

**Comment by richardjgowers** [comment]
Hmm probably silently ignore central if it's in the ligands. Maybe a quick warning or logger message.

**Comment by mikemhenry** [comment]
+1 to delete/ignore it, throw a warning message
