### ISSUE TITLE
How to visualise/inspect trajectories?

### ISSUE THREAD

**Issue by mkrompiec** [OpenFreeEnergy/openfe#564]
How do I visualise (and, generally, extract) trajectories generated during an openfe run? I assume they are saved in the checkpoint.nc files, in a similar fashion as in Perses. Would something similar to https://github.com/choderalab/perses-barnase-barstar-paper/blob/main/scripts/05_analyze/run_make_traj_per_replica.py work? Could someone share a working example?

**Comment by richardjgowers** [comment]
@mkrompiec the checkpoint `.nc` files should be identical to the openmmtools versions you've found yes, these should only contain snapshots for restarts though, the `simulation.nc` will contain the full trajectories.

We're working on an analysis package here: https://github.com/OpenFreeEnergy/openfe_analysis. For now you'll have to download this and install from the source, it will require MDAnalysis (this conda installable https://www.mdanalysis.org/pages/installation_quick_start/)

This is a small script that will a) load the simulation data into an MDAnalysis Universe and b) write it into an xtc.  You could replace the xtc filename with DCD/etc to get other formats.
```python
import MDAnalysis as mda
from openfe_analysis import FEReader


u = mda.Universe('./hybrid_system.pdb', './simulation.nc',
                 format='openfe rfe', state_id=0)  # specify state or replica ID

ag = u.atoms

with mda.Writer('traj.xtc', n_atoms=len(ag)) as w:
    for ts in u.trajectory:
        w.write(ag)
```

**Comment by mkrompiec** [comment]
Awesome, thank you!

**Comment by richardjgowers** [comment]
@mkrompiec forgot to explain above, the `simulation.nc` file will contain many (default 11) replicas, each a different lambda state.  You can therefore write a trajectory for each state, the above code snippet follows lambda=0.  As lambda states are exchanged between replicas, the trajectory will have some discontinuities between frames.  The alternative is specifying `replica_id=0` which would create a trajectory of a constant replica (but the lambda state is changing over time instead).

**Comment by mkrompiec** [comment]
It worked for me, but is it expected that the trajectories don't contain the solvent molecules? The file hybrid_system.pdb also doesn't contain the solvent (water) molecules at all, only the Na+ and Cl- ions surround the ligand or complex. I'm using the OpenFE Showcase notebook.

**Comment by mkrompiec** [comment]
Ah, I see that this behaviour is defined by the settings: `output_indices='not water'` in `simulation_settings`

**Comment by richardjgowers** [comment]
@mkrompiec yep like you've found.  It is a compromise between storage space required and what is most useful.  We're working upstream with openmmtools to get a bit more flexibility in what/when data is stored, then we'll likely have an option for all water that is near the binding pocket.
