### ISSUE TITLE
mixed precision is hard-coded 

### ISSUE THREAD

**Issue by mkrompiec** [OpenFreeEnergy/openfe#566]
It is not possible to run on platforms which don't support mixed precision, like, for example, Apple M1 with OpenCL. Instead of using a hard-coded argument, could the following: 
https://github.com/OpenFreeEnergy/openfe/blob/main/openfe/protocols/openmm_rfe/equil_rfe_methods.py#L677
https://github.com/OpenFreeEnergy/openfe/blob/main/openfe/protocols/openmm_rfe/_rfe_utils/compute.py#L11
take the precision from `engine_settings` instead? Which could perhaps be allowed to be single, mixed or double.

**Comment by IAlibay** [comment]
I believe single precision has been shown to be too inaccurate to provide reliable free energies - I don't think we've tested double.

To be fair OpenCL is generally poorly tested on our end, so it's hard to know exactly what would happen with confidence.

**Comment by mkrompiec** [comment]
Oh, my bad - indeed single precision isn't recommended for FE so perhaps it's better not to allow users to use it.
