### ISSUE TITLE
Version issue with conda install?

### ISSUE THREAD

**Issue by RiesBen** [OpenFreeEnergy/openfe#572]
https://github.com/OpenFreeEnergy/openfe/blob/559fb2f2b3ecc1bcc38265438dc7e709174d20b5/openfecli/commands/quickrun.py#L96C1-L97C1

I installed a new openFE env and tried to set it up as much as possible as a user. (`mamba install openfe`) 
now I get quickrun erros: as `n_retries` is not defined for `execute_DAG`.
 
Is there a wrong version pin of gufe in the "conda-forge branch"?

**Comment by richardjgowers** [comment]
@RiesBen what versions of openfe and gufe does conda tell you you have installed?

**Comment by RiesBen** [comment]
ok got it it was a wrong install on my side!
