### ISSUE TITLE
Solvate with non-cubic boxes

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe#585]
OpenMM now supports non-cubic boxes, we should see if we could pass this as a user input (through SolventComponent?).

**Comment by IAlibay** [comment]
pinging @hannahbaumann

**Comment by richardjgowers** [comment]
As a sanity check, could we first quickly check for a sample set of protein structures (PLB?) how much solvent we can avoid adding and as a post-step quickly check that the benchmarking figures are agreeing with this being quicker.

I'm also curious if aligning the protein's gyration tensor along box primary vectors would help here

**Comment by jameseastwood** [comment]
Can we get a review on this (really the associated [PR](https://app.zenhub.com/workspaces/openfe-6615a0133899140ef86163db/issues/gh/openfreeenergy/openfe/673)) sometime soon? @IAlibay @hannahbaumann Low priority though.
[] Work out if it makes sense
[] Try it out on a few systems
