### ISSUE TITLE
Add convenience methods to AtomMapping

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe#59]
So something that seems to be happening a lot with both drawing out mappings & using the mappings downstream is that we need to have access to:

- mol2_to_mol1_map
- mol1_unique_atoms (i.e. not in the map)
- mol2_unique_atoms (i.e. not in the map)
- atoms in the mapping that change elements

I'm opening this issue so we can consider potentially adding a couple of small methods to AtomMapping to make getting these out more easily.

**Comment by richardjgowers** [comment]
done
