### ISSUE TITLE
Work out what to do with the tyk2 results file

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe#605]
We have two sets ?rbfe_results.tar.gz and results.tar.gz? we need to work out why they both exist and whato do with them.

**Comment by mikemhenry** [comment]
`results.tar.gz` Is not what gets pulled down with fetch, it likely can be scrubbed. I vote we attach `rbfe_results.tar.gz` aka `{protocol}_results.tar.gz` as a release asset for `openfe` then we can use the `latest` trick so we always pull down the latest copy.
