### ISSUE TITLE
docker tests are failing

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe#610]
`test_log_system_probe_unconfigured` seems to be failing.

pinging @mikemhenry

**Comment by mikemhenry** [comment]
I will have to grok this some more, it started awhile ago 
![image](https://github.com/OpenFreeEnergy/openfe/assets/11765982/93bfd31e-f842-48a0-b69c-d340de9e6cbb)

```
     def test_log_system_probe_unconfigured():
        # if probe loggers aren't configured to run, then we shouldn't even call
        # _probe_system()
        logger_names = [
            'openfe.utils.system_probe.log',
            'openfe.utils.system_probe.log.gpu',
            'openfe.utils.system_probe.log.hostname',
        ]
        # check that initial conditions are as expected
        for logger_name in logger_names:
            logger = logging.getLogger(logger_name)
>           assert not logger.isEnabledFor(logging.DEBUG)
E           assert not True
E            +  where True = <bound method Logger.isEnabledFor of <Logger openfe.utils.system_probe.log (DEBUG)>>(10)
E            +    where <bound method Logger.isEnabledFor of <Logger openfe.utils.system_probe.log (DEBUG)>> = <Logger openfe.utils.system_probe.log (DEBUG)>.isEnabledFor
E            +    and   10 = logging.DEBUG

/opt/conda/lib/python3.10/site-packages/openfe/tests/utils/test_system_probe.py:455: AssertionError
```

**Comment by mikemhenry** [comment]
If I build the image locally, I can reproduce the error with:
`docker run --rm ghcr.io/openfreeenergy/openfe:dev pytest --pyargs openfecli --pyargs openfe -v` but if I just run the test that fails, `docker run --rm ghcr.io/openfreeenergy/openfe:dev pytest --pyargs openfecli --pyargs openfe -v -k test_log_system_probe_unconfigured` it passes

**Comment by mikemhenry** [comment]
Wow, if I swap the order I test the packages in, the error goes away... An easy win but the root cause must be that some other test messes `test_log_system_probe_unconfigured` up
