### ISSUE TITLE
Enabling charge changes in RFE protocol

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe#617]
This is the meta issue for allowing charge changes in the RFE protocol.

As of #569 - we have tooling in place to do charge changes, but it needs validation.

Current status:

@hannahbaumann is running CDK2 benchmarks from the FEP+ paper, and will be adding more things as results come through.

**Comment by ijpulidos** [comment]
If it helps, we do a consistency test in perses with a charged host-guest system in https://github.com/choderalab/perses/blob/7eaa1626c7c935f9cc4156f9a53ced3694b40bf0/perses/tests/test_repex.py#L315

Basically it's running the transformation in both directions and check if it's close to zero after some number of iterations. The input data files should live under the `data/host-guest` path in perses
