### ISSUE TITLE
fix codecov logic 

### ISSUE THREAD

**Issue by mikemhenry** [OpenFreeEnergy/openfe#658]
![image](https://github.com/OpenFreeEnergy/openfe/assets/11765982/fddb535b-b8ac-42cc-88fb-347431986e31)

looks like I have a bug where even on the scheduled slow tests, coverage reports are not uploaded:

https://github.com/OpenFreeEnergy/openfe/blob/main/.github/workflows/ci.yaml#L98-L111

Actually looking at the code, it looks like we don't upload on a scheduled run, since we can run into rate limiting when the commit hash doesn't change, I will see if running it manually uploads a coverage report with the slow tests

**Comment by IAlibay** [comment]
I thought we were only going to upload on merge?

**Comment by mikemhenry** [comment]
It looks like that isn't an event we can trigger on, https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push

but looking at our triggers, I think `push` is what we want, since the only time we push to main is (other than yolo moments) is when we merge in a PR. 

https://github.com/OpenFreeEnergy/openfe/blob/main/.github/workflows/ci.yaml#L6-L8


This URL https://github.com/OpenFreeEnergy/openfe/actions/workflows/ci.yaml?query=event%3Apush

Should show every push event that was triggered, and lo and behold https://github.com/OpenFreeEnergy/openfe/actions/runs/6973281698/job/18976990972 it looks like it is working exactly as intended! 
![image](https://github.com/OpenFreeEnergy/openfe/assets/11765982/d6728b16-c41c-4056-b640-70f37ea461d6)
We can also see the coverage differences, so this *should* fix the issue where codecov has a winge about the testing coverage going down, since now it should only compare the same flags, but if it still has issues, we probably just need to add a line of config that only compare coverage of to the same flag.
