### ISSUE TITLE
Consider relaxing upper pin on openff-toolkit

### ISSUE THREAD

**Issue by mikemhenry** [OpenFreeEnergy/openfe#699]
Right now we can't install the latest `openff-toolkit (0.15.1)` with `openfe` since we have a pin:
[`openff-toolkit >=0.13,<0.15`](https://github.com/conda-forge/openfe-feedstock/blob/main/recipe/meta.yaml#L31)

Looking at the changelog https://docs.openforcefield.org/projects/toolkit/en/stable/releasehistory.html some oof the bug fixes in the `0.15.x` line are useful, no relevant API breaks, and enables the use of modern QCFractal. 

I propose we change the pin to `>=0.13,<0.16` so we can guard against future major API breaks, but allow users to install the latest and greatest `openff-toolkit`

Let me know your thoughts 
@richardjgowers @IAlibay @hannahbaumann @dwhswenson @RiesBen

**Comment by IAlibay** [comment]
Assuming the QA tests you're running on 8.1.1 + openff 0.15.x come back positive this looks like a good idea to me!

**Comment by mattwthompson** [comment]
This looks done? https://github.com/conda-forge/gufe-feedstock/pull/34/files

**Comment by IAlibay** [comment]
Closing as completed - we should reopen this issue when we consider off tk 0.17
