### ISSUE TITLE
`output_structure` and `output_filename` are present and unused in MDOuputSettings

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe#715]
Since the settings class inherits from OutputSettings, the `output_structure` and `output_filename` entries are inherited but not used for anything.

**Comment by hannahbaumann** [comment]
I also just realized that this is confusing as I'm writing the MD example notebook. Should we create a base OutputSettings class and a MultiStateOutputSettings class (where we move the `output_structure` and `output_filename`, or do you think we should leave it as is for now, @richardjgowers ?
