### ISSUE TITLE
Visualisation on deserialised edge throws error:

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe#74]
Sorry don't have time to get the full trace again, but this throws some index errors in the visualisation code paths:

```python

# load a new network from this graphml representation
with open('network_store.graphml', 'r') as file:
    network_data = file.read()
    
new_network = Network.from_graphml(network_data)

# should trigger a display of the first edge
[edge for edge in new_network.edges][0]
```

**Comment by richardjgowers** [comment]
Couldn't reproduce this locally...

**Comment by IAlibay** [comment]
interesting, I'll retry a bit later

**Comment by dwhswenson** [comment]
I think I'm having the same problem. This is (the only thing, I think) blocking #92. It looks like we're not serializing the hydrogens, but the hydrogens are included in the atom mapping. When do we add the hydrogens in?

```python
rdmol1 = mapping.mol1.to_rdkit()
rdmol2 = mapping.mol2.to_rdkit()
for mol in [rdmol1, rdmol2]:
    print(mol.GetProp("ofe-name"), mol.GetNumAtoms())

print(mapping.mol1_to_mol2)
```

```
benzene 6
anisole 8
{0: 5, 1: 6, 2: 7, 3: 8, 4: 9, 5: 10, 6: 11, 7: 12, 8: 13, 9: 14, 10: 2, 11: 15}
```

**Comment by IAlibay** [comment]
I don't think we're explicitly adding hydrogens anywhere. We should be loading from file without converting to implicit where possible though.

**Comment by dwhswenson** [comment]
Yep. [`SDMolSupplier.setData` has a `removeHs` parameter that defaults to `True`](https://www.rdkit.org/docs/cppapi/classRDKit_1_1SDMolSupplier.html#a349ea3e15714b648940edf6d35d93ff9). That looks to be the culprit. Will open a PR soon.

**Comment by IAlibay** [comment]
Thanks, I was just about ask about that 🙃
