### ISSUE TITLE
[docs] Revise landing page icon order & instructions?

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe#746]
Right now if I click on the docs as a new person the only thing I know is that the install instructions is the first thing I need to look at. Afterwards I have no idea what I should look at next if I want to carry out calculation X (or if calculation X is even supported).

Maybe we should have:

- A list of available tooling/protocols and what docs to look at (looking for X?, here is Y to achieve it)
- A kind of "hint at where you should be looking at in what order", maybe tutorials, then userguide then cookbook?

**Comment by richardjgowers** [comment]
There's 8 buttons on the homepage, currently
- Installation
- Tutorials
- User guide
- API ref
- Cookbook
- CLI
- Changelog
- RFE Protocol

I think the only thing I'd change would be RFE Protocol to Ecosystem, which would link out to the ecosystem page on the main website.

The buttons are correctly ordered, the text on each could be refined to make it clearer that they're in an order and what each button actually means.

We could/should also have better homepage text above the buttons.
