### ISSUE TITLE
PlainMDProtocolSettings is using default BaseForceFieldSettings instead of OpenMMSystemGeneratorFFSettings

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe#768]
Both the RFE and AFE protocols set their `forcefield_settings` entries to specify the OpenMMSystemGeneratorFFSettings, but the PlainMDProtocolSettings doesn't.

Given that the protocol currently only specifically works with SystemGenerator - does it make sense to set that specifically?

The main thing here is that otherwise docs don't work amazingly well (as in the MD protocol points to the base FF settings which don't include much).

**Comment by richardjgowers** [comment]
Yep makes sense.
