### ISSUE TITLE
MBAR overlap matrix sometimes wrong

### ISSUE THREAD

**Issue by hannahbaumann** [OpenFreeEnergy/openfe#806]
In some cases the MBAR overlap matrix is wrong (not adding up to 1 in the rows/columns, while for other cases it is correct.
![mbar_overlap_matrix](https://github.com/OpenFreeEnergy/openfe/assets/43765638/b30ddf80-307c-428f-bfb8-13245e0326ad)
![mbar_overlap_matrix](https://github.com/OpenFreeEnergy/openfe/assets/43765638/9f187959-400b-4a75-a547-5a88bb19303d)

**Comment by IAlibay** [comment]
Part of what confuses me here is that .01 is darker than 0.89 :/

Do you have the underlying matrix data on hand?

**Comment by IAlibay** [comment]
As a separate note - your previous example of a 0.70 data point being problematic is also very important to raise here. This mean it's unlikely to be some kind of near 1.0 overflow issue.

**Comment by IAlibay** [comment]
P.S. the pymbar 4 code did change for this code, going from what used to be an element-wise multiplication to a matrix multiplication of the weight matrix. This _could_ be part of an artifact of using too old a pymbar version with a newer numpy version.

**Comment by hannahbaumann** [comment]
This is the overlap matrix for the plot on the top:
```
[[4.04963280e-01 2.64851626e-01 1.55960834e-01 8.70071466e-02
  4.65819362e-02 2.21166590e-02 5.28613476e-19 1.21332039e-39
  9.53847574e-47 1.08409130e-49 1.00129930e-50]
 [2.64851626e-01 2.38999336e-01 1.90795611e-01 1.39227718e-01
  9.35391162e-02 5.40680743e-02 4.14462223e-18 9.51310340e-39
  7.47869291e-46 8.49987577e-49 7.85074074e-50]
 [1.55960834e-01 1.90795611e-01 1.99215052e-01 1.82450137e-01
  1.49240018e-01 1.03819831e-01 2.12518612e-17 4.87791510e-38
  3.83475587e-45 4.35837503e-48 4.02552618e-49]
 [8.70071466e-02 1.39227718e-01 1.82450137e-01 2.03476122e-01
  2.00318604e-01 1.69001754e-01 7.63228831e-17 1.75183030e-37
  1.37719525e-44 1.56524525e-47 1.44570756e-48]
 [4.65819362e-02 9.35391162e-02 1.49240018e-01 2.00318604e-01
  2.39174175e-01 2.52627633e-01 2.01399730e-16 4.62270467e-37
  3.63412308e-44 4.13034672e-47 3.81491237e-48]
 [2.21166590e-02 5.40680743e-02 1.03819831e-01 1.69001754e-01
  2.52627633e-01 3.79847531e-01 3.76232213e-16 8.63561442e-37
  6.78885803e-44 7.71584694e-47 7.12658815e-48]
 [5.28613476e-19 4.14462223e-18 2.12518612e-17 7.63228831e-17
  2.01399730e-16 3.76232213e-16 **1.01326575e+00** 8.95334208e-03
  5.08819552e-07 9.41453345e-09 2.77171908e-09]
 [1.21332039e-39 9.51310340e-39 4.87791510e-38 1.75183030e-37
  4.62270467e-37 8.63561442e-37 8.95334208e-03 8.92862646e-01
  1.07782005e-01 9.27776485e-03 3.34696054e-03]
 [9.53847574e-47 7.47869291e-46 3.83475587e-45 1.37719525e-44
  3.63412308e-44 6.78885803e-44 5.08819552e-07 1.07782005e-01
  5.54361284e-01 2.25806184e-01 1.34272920e-01]
 [1.08409130e-49 8.49987577e-49 4.35837503e-48 1.56524525e-47
  4.13034672e-47 7.71584694e-47 9.41453345e-09 9.27776485e-03
  2.25806184e-01 3.94054662e-01 3.93084315e-01]
 [1.00129930e-50 7.85074074e-50 4.02552618e-49 1.44570756e-48
  3.81491237e-48 7.12658815e-48 2.77171908e-09 3.34696054e-03
  1.34272920e-01 3.93084315e-01 4.91518742e-01]]
```
Note in bold is the number that become 0.01 in the plot.

**Comment by IAlibay** [comment]
> Our plotting code does a >0.995 check

I came back to this issue ahead of today's call and realised that we did not have that check, but both the original alchemical analysis code and alchemlyb does - must have been an error whilst I was modifying the code. I've opened PR #811 to address this.

**Comment by IAlibay** [comment]
Second problematic matrix: 

[[2.34151792e-001 1.39888121e-001 7.84874621e-002 4.18336072e-002
 2.05969028e-002 7.26433700e-003 8.59588359e-069 9.82810344e-154
 2.86854631e-174 3.61851838e-179 2.03347234e-180]
 [1.39888121e-001 1.33087532e-001 1.06283463e-001 7.48596022e-002
 4.71944621e-002 2.09090412e-002 2.61632960e-069 9.87687147e-154
 3.04564890e-174 1.01323581e-178 5.71180108e-180]
 [7.84874621e-002 1.06283463e-001 1.12085643e-001 1.01164236e-001
 8.02528014e-002 4.39486161e-002 4.65970677e-070 5.76131562e-154
 2.05138486e-174 1.68711540e-178 9.52136287e-180]
 [4.18336072e-002 7.48596022e-002 1.01164236e-001 1.15030824e-001
 1.12925630e-001 7.64083221e-002 5.56609447e-071 2.25203208e-154
 1.10970982e-174 1.88729763e-178 1.06553350e-179]
 [2.05969028e-002 4.71944621e-002 8.02528014e-002 1.12925630e-001
 1.37008472e-001 1.24243953e-001 4.63825760e-072 6.26556483e-155
 5.47382223e-175 1.47688013e-178 8.33933879e-180]
 [7.26433700e-003 2.09090412e-002 4.39486161e-002 7.64083221e-002
 1.24243953e-001 2.49447953e-001 2.15384511e-073 9.78751994e-156
 1.89651311e-175 6.46075564e-179 3.64830252e-180]
 [8.59588359e-069 2.61632960e-069 4.65970677e-070 5.56609447e-071
4.63825760e-072 2.15384511e-073 1.54873255e+000 2.33585672e-002
2.78272533e-006 4.61271012e-008 9.81085527e-009]
 [9.82810344e-154 9.87687147e-154 5.76131562e-154 2.25203208e-154
 6.26556483e-155 9.78751994e-156 2.33585672e-002 1.36721112e+000
 1.64391352e-001 1.39600025e-002 4.59238353e-003]
 [2.86854631e-174 3.04564890e-174 2.05138486e-174 1.10970982e-174
 5.47382223e-175 1.89651311e-175 2.78272533e-006 1.64391352e-001
 8.87029135e-001 3.45990080e-001 1.76251997e-001]
 [3.61851838e-179 1.01323581e-178 1.68711540e-178 1.88729763e-178
 1.47688013e-178 6.46075564e-179 4.61271012e-008 1.39600025e-002
 3.45990080e-001 6.27268856e-001 5.86475486e-001]
 [2.03347234e-180 5.71180108e-180 9.52136287e-180 1.06553350e-179
 8.33933879e-180 3.64830252e-180 9.81085527e-009 4.59238353e-003
 1.76251997e-001 5.86475486e-001 8.06379597e-001]]
