### ISSUE TITLE
docs: links in cookbook from nblink don't work

### ISSUE THREAD

**Issue by richardjgowers** [OpenFreeEnergy/openfe#807]
The "Download Notebook" link at the top of e.g. this page:

https://docs.openfree.energy/en/stable/cookbook/loading_molecules.html

Gives a 404.  This is because it's searching for ExampleNotebooks/ from within the openfe repo

**Comment by IAlibay** [comment]
related to https://github.com/OpenFreeEnergy/openfe/issues/784 ?

**Comment by richardjgowers** [comment]
ah yeah this is a duplicate
