### ISSUE TITLE
Docker image tests are failing

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe#816]
cc @mikemhenry 

CI for the docker image tests are failing with:

```
____________________ TestOFECommandPlugin.test_plugin_setup ____________________

self = <openfecli.tests.test_plugins.TestOFECommandPlugin object at 0x7f8ba3c41a80>

    def test_plugin_setup(self):
>       assert self.plugin.command is fake
E       AttributeError: 'TestOFECommandPlugin' object has no attribute 'plugin'
```

I remember raising a similar issue not too long ago, so apologies if it's a known issue / WIP!

**Comment by mikemhenry** [comment]
Oh man, I think that one had to do with the order we ran the test fixtures in since one fixture mutates a global state without resetting it... but this one looks a bit different, but might have the same issue?
