### ISSUE TITLE
2 warnings when building docs 

### ISSUE THREAD

**Issue by mikemhenry** [OpenFreeEnergy/openfe#819]
`/home/mmh/micromamba/envs/openfe-docs/lib/python3.10/site-packages/gufe/settings/models.py:docstring of gufe.settings.models.OpenMMSystemGeneratorFFSettings:1: WARNING: duplicate object description of gufe.settings.models.OpenMMSystemGeneratorFFSettings, other instance in reference/api/openmm_rfe, use :noindex: for one of them`

`/home/mmh/micromamba/envs/openfe-docs/lib/python3.10/site-packages/gufe/settings/models.py:docstring of gufe.settings.models.ThermoSettings:1: WARNING: duplicate object description of gufe.settings.models.ThermoSettings, other instance in reference/api/openmm_rfe, use :noindex: for one of them`

It _might_ be a local thing, but I did run `make clean` first

**Comment by richardjgowers** [comment]
@mikemhenry have you also deleted your `generated/` directory?  make clean doesn't do that

**Comment by mikemhenry** [comment]
Gah this is the second time I've been tripped up by this (I think last time the word "generated" was in the warning which was a good hint), sorry for the noise
