### ISSUE TITLE
Unpin rdkit on mypy

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe#844]
Opening up this PR so we remember to do this.

@mikemhenry I believe you put the pin in, do you know if there's an issue upstream to work out why this duplicate self is happening?

**Comment by mikemhenry** [comment]
Yes the error was that there was a syntax error with the rdkit typing stubs and that pinned version fixed it, I can try and fix that on #733

**Comment by mikemhenry** [comment]
This is the mypy error: `/home/runner/micromamba/envs/openfe_env/lib/python3.11/site-packages/rdkit-stubs/Chem/rdMolDescriptors.pyi:247: error: Duplicate argument "self" in function definition` seen with `rdkit 2024.03.2 py311h1d78c4b_0 conda-forge`

I will see if `2023.09.5` works but with python relaxed (it was pined to 3.9 which was causing the issues with the env solving).

**Comment by mikemhenry** [comment]
Also see https://github.com/rdkit/rdkit/issues/7401
