### ISSUE TITLE
4-point water models fail with RBFE Protocol

### ISSUE THREAD

**Issue by palominohernandez** [OpenFreeEnergy/openfe#881]
Dear all,

I tried different 4-point water models like tip4pew (and opc) into the setup of `RelativeHybridTopologyProtocol()`.

Apparently, when running the calculation I get the following error:

> ValueError: Simulations with virtual sites without velocity reassignments are unstable in openmmtools

An option "technically" should be to set `reassign_velocities = True` in the protocol [1], but I think that this might not be the correct approach for a simulation as this might reset the velocities at every MC move. 

Let me know if there is a way of overcoming this, or if I should stick with 3-point water models. 

Thanks!
Oscar

[1]https://docs.openfree.energy/en/v0.10.1/reference/api/openmm_rfe.html#openfe.protocols.openmm_rfe.equil_rfe_settings.IntegratorSettings.reassign_velocities

**Comment by IAlibay** [comment]
@palominohernandez - the answer here is indeed to set `reassign_velocities=True`. There's a known issue with the way in which the replica exchange sampler assigns velocities after swaps that seems to fail with dummy atoms. Our testing on hydration free energies indicates that, resetting velocities after every exchange attempt does not lead to any significant changes in the free energy estiamtes. We note that more work is necessary here, this is a use case with little use and more validation by members of the community would be appreciated.
