### ISSUE TITLE
Add nvidia-smi step to GPU runners

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe#913]
Ethan rightly recommends we have that to make sure we have a GPU.

**Comment by mikemhenry** [comment]
We are testing on CPU runners right now so I expect `nvidia-smi` to fail

**Comment by IAlibay** [comment]
@mikemhenry this is more a to-do for later 😅

**Comment by ethanholz** [comment]
First, is this something I could open a PR on? I am more than willing to help build this out with you all just would want some direction on how I can be of use in getting this running.

One thing I have been doing when testing on both GPU and CPU is to just add a step that looks like this:
```yaml
- name: Check for nvidia-smi
   run: "nvidia-smi || true"
```

That way you get to see if it works and if not it doesn't completely fail the run.

**Comment by mikemhenry** [comment]
Something else I like to add to "fail fast" is `python -m openmm.testInstallation` (if doing something that is openmm related) since then its easy to check if OpenMM can get a GPU and the CUDA platform is working

**Comment by ethanholz** [comment]
This is something we are also working on. I have isolated the part of that script for identifying platforms into something that provides different exit codes based on what is being tested (i.e. if CUDA exists in an OpenMM context return), more than happy to make this more broadly available via the `openmm-gpu-test` repo if there is interest.
