### ISSUE TITLE
`ProtocolDAGResult`s produced by `RelativeHybridTopologyProtocol` can grow very large in typical usage

### ISSUE THREAD

**Issue by dotsdl** [OpenFreeEnergy/openfe#926]
A `ProtocolDAGResult` produced by the `RelativeHybridTopologyProtocol` for one of ASAP Discovery's lead optimization programs, performed on `alchemiscale` using `openfe` 1.0.1, measures ~32 MiB when serialized directly to JSON. This is rather large on its own, but results in extremely slow result retrieval for an `AlchemicalNetwork` with ~3000 of these objects, resulting in ~95 GiB of memory usage to load them all at once. Many user machines would not be able to manage this.

We did not see this kind of behavior in `openfe` 0.14.0, indicating that this may be due to the `structural_analysis` outputs that were added in the releases following this. This gives RMSDs for various components over time, for every replica, and at least appears to be the largest new data structure in the `ProtocolDAGResult` object.

There are several options available to address this, none of which are mutually exclusive:
1. Expose a setting for this protocol allowing users to set the frequency with which RMSDs are recorded in the `structural_analysis` outputs, including setting the frequency to `0` (disabling them completely).
2. Make the `structural_analysis` outputs `numpy` arrays instead of lists, then convert to bytes->base64 encoding. Will also help with speeding up [KeyedChain](https://github.com/OpenFreeEnergy/gufe/pull/286) representation generation, which will matter if this protocol uses more than one `ProtocolUnit` with dependencies in the future.
3. Make the `RelativeHybridTopologyProtocolResult` object take only what it needs from the `ProtocolDAGResult` `ProtocolUnitResult`s it aggregates, instead of holding on to those `ProtocolUnitResult`s in memory. This would allow the `ProtocolUnitResult`s to be garbage collected more easily while retaining the `RelativeHybridTopologyProtocolResult` a user likely wants.

A more invasive change would be to move `structural_analysis` outputs to their own file, or if they are already recorded in file outputs, to keep them there. This has the downside that this data would not be readily available to users of `alchemiscale` until result file retrieval is possible with that system.

**Comment by dotsdl** [comment]
See here for the source of this issue: https://github.com/asapdiscovery/asapdiscovery/issues/1180

**Comment by JenkeScheen** [comment]
Just to create some practical context here: we ran a `MinimalRedundantNetwork` network in production of about 300 compounds. `gather`ing this network did not succeed on my or @dotsdl 's machines, ultimately it took a machine with a 250GB swap disk. It's critical that this is fixed if we want to be able to run OpenFE at larger scales in production.

**Comment by IAlibay** [comment]
> It's critical that this is fixed if we want to be able to run OpenFE at larger scales in production.

For the sake of anyone looking here - this is solely if you are using alchemiscale, normal OpenFE usage is not affected by this.

**Comment by dotsdl** [comment]
@JenkeScheen are you using `structural_analysis` outputs at all, e.g. RMSDs?

**Comment by JenkeScheen** [comment]
no

**Comment by dotsdl** [comment]
Awesome, thank you! In today's call @IAlibay suggested removing the `structural_analysis` outputs from the `RelativeHybridTopologyProtocol`'s `ProtocolUnitResult`, since this was injected to the output with `alchemiscale` users in mind, but likely isn't being used due to it only being made available in the recent `alchemiscale` 0.5.0.

Longer term, we will explore solutions to reduce the size of `ProtocolDAGResult` objects by choosing a different serialization approach from JSON, such as `msgpack`.
