### ISSUE TITLE
OpenFE release 1.1.0

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe#938]
We need a release.

To do this we need to:
- [x] QA with different box types
  - [x] Cubic
  - [x] Dodecahedron
- [x] Cut a release
- [x] Pass it through to conda-forge
- [x] Profit

**Comment by ijpulidos** [comment]
Excited to see the results of performance gain on using different geometries for the boxes and see if that affects the estimates.

**Comment by hannahbaumann** [comment]
Results from the 1.0rc QA for TYK2:
[cinnabar_tyk2_1.0rc.csv](https://github.com/user-attachments/files/17115952/cinnabar_tyk2_1.0rc.csv)

**Comment by IAlibay** [comment]
Pins that need increasing:

* OpenMM version where non-cubic boxes was introduced.
* Pydantic version where pydantic.v1 was introducted.

**Comment by ijpulidos** [comment]
Not a real expert, but I think these look very good! And the performance gain in the `complex` leg of the simulation seems to be up to ~40% for the dodecahedron compared to the cubic geometry. Great to see this!

**Comment by ijpulidos** [comment]
Quick question, what's the PR or set of changes that enable this feature? Just considering checking it just to see if this affects us in `feflow`. I tried looking through the list of PRs but couldn't find it, I probably missed some keyword.

**Comment by IAlibay** [comment]
@ijpulidos it's https://github.com/OpenFreeEnergy/openfe/pull/673

I had a look through on FEFlow and I'm pretty sure it'll just "work" (we should add a test though).

**Comment by IAlibay** [comment]
Closing as completed.
