### ISSUE TITLE
Two errors in minimal redundant network with Kartograph Mapper

### ISSUE THREAD

**Issue by AntoniaRabe** [OpenFreeEnergy/openfe#948]
I tried to calculate an edge that does not have a perfect mapping and got two error messages. Can you please explain the meaning behind them? What exactly is the issue here?

- 0_easy_rbfe_A_complex_B_complex
…
Done with all simulations! Analyzing the results....
Here is the result: dG = None ± None
Error: The protocol unit 'A - lig to B - lig repeat 2 generation 0' failed with the error message:
IndexError: list index out of range
 
- 1_easy_rbfe_A_solvent_B_solvent
…
Parameterizing molecules
[13:46:05] Can't kekulize mol.  Unkekulized atoms: 0 1 2 16 17
Done with all simulations! Analyzing the results....
Here is the result: dG = None ± None
Error: The protocol unit 'A - lig to B - lig repeat 2 generation 0' failed with the error message:
ValueError: Cannot construct openff.toolkit.topology.Molecule from <rdkit.Chem.rdchem.Mol object at 0x7f27f50919a0>
No registered toolkits can provide the capability "from_object" for args "(<rdkit.Chem.rdchem.Mol object at 0x7f27f50919a0>,)" and kwargs "{'allow_undefined_stereo': True, '_cls': <class 'openff.toolkit.topology.molecule.Molecule'>}"

**Comment by IAlibay** [comment]
@AntoniaRabe are there more error outputs you can provide? 

Also can you confirm what versions of OpenFE, rdkit, and openff-toolkit you are using?

**Comment by IAlibay** [comment]
From an initial look, it seems like your input molecules are incorrectly defined.

**Comment by AntoniaRabe** [comment]
Hello Mr. Alibay,


thank you for the quick response.

Versions:
openfe 1.0.1
openff-toolkit 0.15.2

rdkit 2023.03.3


My calculations are with SMN2 ligands. Two ligands don't seem to fit the binding pose from the crystal structure: 8CF2 and 8R63 that's why I anticipated a high rmsd or an error already. I just don't really know the specifics of the error. For the other ligands, e.g. 8R62, everything went fine.

For the two calculations all the files are attached.

Thanks for your help.

BR,
Antonia


___________________________________
Antonia Rabe
B. Sc. BMC
Masterstudent @ CzodrowskiLab

Johannes Gutenberg University Mainz
Department of Chemistry
Institute of Physical Chemistry
Duesbergweg 10-14
55128 Mainz

***@***.***

________________________________
Von: Irfan Alibay ***@***.***>
Gesendet: Samstag, 5. Oktober 2024 15:53:49
An: OpenFreeEnergy/openfe
Cc: Rabe, Antonia Marie; Mention
Betreff: Re: [OpenFreeEnergy/openfe] Two errors in minimal redundant network with Kartograph Mapper (Issue #948)


From an initial look, it seems like your input molecules are incorrectly defined.

**Comment by AntoniaRabe** [comment]
Hello, as I wrote before I am aware that the program searches for a common substructure and we tried to align the ligands. Are there any news on how to interpret the error messages and thus, how to move forward with the ligands?

**Comment by atravitz** [comment]
@IAlibay could you forward me the email with the attachments from this user? Looks like it was sent the day before I joined.

**Comment by IAlibay** [comment]
@AntoniaRabe I'm so sorry for not following up, I don't believe that I ever received any attached ligand files either on this issue or via email. Could you try to resend this please?

**Comment by AntoniaRabe** [comment]
Yes, of course. Something went wrong there. Here are the whole output files and also the ligand (sdf) input.
[issue_948.zip](https://github.com/user-attachments/files/17574413/issue_948.zip)
[Structures.txt](https://github.com/user-attachments/files/17574441/Structures.txt)

**Comment by IAlibay** [comment]
@AntoniaRabe thanks for sending these through.

Having a brief look through your input files, the complex simulation has no mapped atoms between the two ligands, which is why you are getting that IndexError - i.e. the Protocol does not know how to create the hybrid topology for the alchemical transformation between the two ligands.

For the solvent simulation it looks like only one atom is mapped between the two end state ligands, which isn't the reason for the failure but would definitely would cause some simulation issues. The exact issue you're facing is something that needs a bit more work - it looks like some issue with force field assignment.

**Comment by AntoniaRabe** [comment]
Thank you very much for your responses and your insights. I adapted my network now to have better alignment and excluded some ligands.
