### ISSUE TITLE
`PlainMDProtocol` doesn't seem to catch `settings.solvation_settings.box_shape = "dodecahedron"`

### ISSUE THREAD

**Issue by JenkeScheen** [OpenFreeEnergy/openfe#954]
Adjusted from [your plain MD tutorial](https://docs.openfree.energy/en/stable/tutorials/md_tutorial.html), I'm trying to make some MD inputs with dodecahedral water boxes. This is with `openfe           1.1.0    pyhd8ed1ab_1  conda-forge`. Here's an example:
```
import os
import openfe
from openfe import (
    ChemicalSystem,
    ProteinComponent,
    SmallMoleculeComponent,
    SolventComponent,
)
from openff.units import unit
from openfe.protocols.openmm_md.plain_md_methods import PlainMDProtocol

ligand = SmallMoleculeComponent.from_sdf_file("ligand.sdf")

# Define the solvent environment and protein structure
solvent = SolventComponent(ion_concentration=0.15 * unit.molar)
protein = ProteinComponent.from_pdb_file("protein.pdb", name="TYK2")

# create the ChemicalSystem
system = ChemicalSystem(
    {"ligand": ligand, "protein": protein, "solvent": solvent},
    name=f"tyk2_ligand_{protein.name}",
)

settings = PlainMDProtocol.default_settings()
settings.forcefield_settings.small_molecule_forcefield = "openff-2.2.0"
settings.simulation_settings.production_length = 5 * unit.nanosecond
settings.solvation_settings.box_shape = "dodecahedron"

# Creating the Protocol
protocol = PlainMDProtocol(settings=settings)
nontransformation = openfe.NonTransformation(
    system=system,
    protocol=protocol,  # use protocol created above
    name=f"{system.name}",
)
os.makedirs("md_production/")
nontransformation.dump(
    "md_production/md_factory.json",
)
```
Once that's finished I enter `md_production` and run `openfe quickrun md_factory.json -o results.json -d output` which I interrupt when minimization starts:
```
Loading file...
Planning simulations for this edge...
Starting the simulations for this edge...
SYSTEM CONFIG DETAILS:
INFO:openfe.utils.system_probe.log:SYSTEM CONFIG DETAILS:
hostname: 'JSMBP.local'
INFO:openfe.utils.system_probe.log.hostname:hostname: 'JSMBP.local'
CUDA-based GPU not found
INFO:openfe.utils.system_probe.log.gpu:CUDA-based GPU not found
Memory used: 28.8G (55.2%)
INFO:openfe.utils.system_probe.log:Memory used: 28.8G (55.2%)
output/scratch_PlainMDProtocolUnit-c44a0e92134d43c2b17c9f991bf84c07_attempt_0: 49% full (951.8G free)
INFO:openfe.utils.system_probe.log:output/scratch_PlainMDProtocolUnit-c44a0e92134d43c2b17c9f991bf84c07_attempt_0: 49% full (951.8G free)
Creating system
INFO:gufekey.openfe.protocols.openmm_md.plain_md_methods.PlainMDProtocolUnit:Creating system
WARNING:py.warnings:/Users/jenkescheen/micromamba/envs/asapdiscovery/lib/python3.10/site-packages/openfe/protocols/openmm_rfe/_rfe_utils/compute.py:56: UserWarning: Non-GPU platform selected: CPU, this may significantly impact simulation performance
  warnings.warn(wmsg)

WARNING:root:Non-GPU platform selected: CPU, this may significantly impact simulation performance
minimizing systems
INFO:openfe.protocols.openmm_md.plain_md_methods:minimizing systems
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
Aborted!
```
Then when I enter `./output/shared[..]/` and check `system.pdb` it's actually cubic: 
![image](https://github.com/user-attachments/assets/0fe107c1-bf92-4dbf-8504-a6d478fe5d54)

Should I be defining the box shape settings further upstream instead? Attaching input files for repro in case it's an actual bug. 
[Archive.zip](https://github.com/user-attachments/files/17329890/Archive.zip)

**Comment by IAlibay** [comment]
Thanks so much for reporting this @JenkeScheen - this is indeed very strange. 

 > Should I be defining the box shape settings further upstream instead?

No that should be the right place. We'll need to dig into this a bit.

**Comment by IAlibay** [comment]
So briefly looking at the box vectors, it looks like the simulation is probably indeed a dodecahedron, but the simulation isn't wrapped back into the cell - still digging into this though.

**Comment by IAlibay** [comment]
@JenkeScheen looking at things, I'm reasonably convinced that this is purely an imaging issue - openmm is simulating a dodecahedron. A look at the box vectors shows the box type I'm expecting.

I ran the above, took the XTC and imaged it with cpptraj:

```bash
cpptraj -p system.pdb << EOF
trajin simulation.xtc
autoimage :1 center familiar origin
trajout imaged.xtc
EOF
```

And go the following dodecahedral system:

![imaged](https://github.com/user-attachments/assets/ea990593-c647-403c-959a-3bc704b8942c)

Could you confirm on your end that imaging the system (with whatever analysis tool you prefer) works?

**Comment by JenkeScheen** [comment]
confirmed!
