### ISSUE TITLE
Support cofactors via the CLI

### ISSUE THREAD

**Issue by jthorton** [OpenFreeEnergy/openfe#983]
We now support the use of cofactors via the API so we should make this easier for CLI users as well!

**Comment by atravitz** [comment]
@jthorton looks like it's already implemented [here](https://github.com/OpenFreeEnergy/openfe/blob/be2bb5e0fb309edfd1d9cfd86bec52dd04309b49/openfecli/commands/plan_rbfe_network.py#L55) - did you mean any additional behavior?

**Comment by jthorton** [comment]
Well, that was easy, yes I think that's all we need!
