### ISSUE TITLE
Add CITATION.cff to repos

### ISSUE THREAD

**Issue by richardjgowers** [OpenFreeEnergy/openfe#99]

**Comment by mikemhenry** [comment]
So do we also want to get zenodo setup as well? Also which repos? I was thinking `openfe` `lomap` and `ExampleNotebooks`

**Comment by richardjgowers** [comment]
Hold off on lomap since it’s already got a citation route, but yes to
Notebooks

**Comment by mikemhenry** [comment]
@richardjgowers @dwhswenson @IAlibay 
Could you post your orcid? Thanks!

**Comment by mikemhenry** [comment]
Cool, one #111 is merged I'll do the same for the notebook (plus update relevant metadata)
